server:
    port: 9908

spring:
    thymeleaf:
        cache: false
    devtools:
        livereload:
            enabled: true
    profiles:
        include:
            - base
        active: local
