server:
    port: 9908

spring:
    thymeleaf:
        cache: false
    devtools:
        livereload:
            enabled: true
    profiles:
        active: local
        include:
            - base
            - base-${spring.profiles.active}

